# SQLite
spring.datasource.url=jdbc:sqlite:photo_app.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Minio
minio.endpoint=http://127.0.0.1:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=photos
